# Generated by Django 3.2.9 on 2021-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=1)),
                ('expiry', models.DateTimeField(verbose_name='expiry date')),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
            ],
        ),
    ]
