# Generated by Django 3.2.9 on 2021-11-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiry',
            field=models.DateField(),
        ),
    ]
